### PR TITLE
Key intra grouping

### PR DESCRIPTION
**Pull request by robUx4**
The code is the same for `KEY_FRAME` and `INTRA_ONLY_FRAME`, no need to have two if {}.

### CODE REVIEW

**Comment by peterderivaz** [comment]
Thanks, this looks like a good simplification.  At the moment the spec is frozen, but if it needs to unfreeze for a normative change we should be allowed to merge this as well.

**Comment by peterderivaz** [comment]
The working group decided not to adopt this change on the grounds that companies have started implementation and they prefer the syntax tables not to change unless really necessary as the tables are used in the documentation and design.

**Comment by kqyang** [comment]
https://github.com/AOMediaCodec/av1-spec/pull/155#issuecomment-411174604 is not convincing to me. This change does not alter the semantics. Why would it be a problem for companies who have started the implementation? 

This simplification avoids confusions, saves unnecessary processing when parsing the bitstreams.

**Comment by jbkempf** [comment]
As 1.1.0 is coming, can we re-open this?

**Comment by kodawah** [comment]
> As 1.1.0 is coming, can we re-open this?

I support this suggestion

**Comment by kqyang** [comment]
+1

**Comment by tmatth** [comment]
+1

**Comment by peterderivaz** [comment]
I've reopened this so the decision can be reviewed on the Tuesday call.
By the way, there is a very similar open pull request #188 .  To my eyes, #188 looks even better than this one (the condition on line 732 is simplified, and another condition on line 788 is removed), do others agree?

**Comment by peterderivaz** [comment]
Thanks for the suggestion, the working group has accepted these changes via the #188 pull request which essentially duplicates this plus an additional clean up.

**Pull request closed without merging**
