### PR TITLE
[OBO mhoro] Add eight additional preconfigured scalability modes

### PR DESCRIPTION
**Pull request by louquillio**
Added on behalf of @mhoro

### CODE REVIEW

**Comment by louquillio** [comment]
Note that the core textual changes are represented here:

https://github.com/mhoro/av1-spec/commit/18221f6ec31379c6cf7005cc325aa248b12dc11c

This PR additionally removes a bunch of trailing spaces from the document, by way of cleanup, as these are significant in Markdown.

**Review by mhoro — APPROVED** [review]
The changes that Lou made on my behalf and the changes that were subsequently added by Lou (on behalf of Alex E.) look good to me.   One question (for Alex): do we plan add figures for the three-spatial layer structures that you have added?

**Comment by eleft** [comment]
Yes, I will add the figures later today or tomorrow the latest.

**Comment by peterderivaz** [comment]
This has been approved on the call, but has merge conflicts that need to be resolved.

**Comment by mhoro** [comment]
If I am reading the conflict correctly, it appears that there is a difference in the definition of spatial_layers_cnt_minus_1 between the master and the branch.  It looks to me like the definition in the master is correct (i.e., the master uses "coded video sequence" in lieu of "video sequence."

I will attempt to resolve the conflict.

**Pull request merged**
