### PR TITLE
Reduce the precision of SGR for 12 bit streams to ease SIMD processing

### PR DESCRIPTION
**Pull request by jbkempf**
Reference: https://bugs.chromium.org/p/aomedia/issues/detail?id=2269

Signed-off-by: Jean-Baptiste Kempf <jb@videolan.org>

### CODE REVIEW

**Comment by peterderivaz** [comment]
Did you see my suggested specification changes on the [patchset](https://aomedia-review.googlesource.com/c/aom/+/76064) ?

At the moment, this pull request seems incomplete.  As far as I can see, a new global variable SGRProjPrecision is defined, but never used.

**Comment by magwyz** [comment]
Yes sorry, the pull request is incomplete because of me. @jbkempf will update and fix it.
Meanwhile, the complete version should be there: https://github.com/magwyz/av1-spec/commit/c17ac16346544c5fb0d471c87325a034b6fb6258

**Comment by jbkempf** [comment]
Oww. I'm sorry. Fixing it now.

**Comment by jbkempf** [comment]
Fixed.

**Comment by peterderivaz** [comment]
Bug has been marked as won't fix

**Pull request closed without merging**
